## 1) Generate an array of zeroes using inbuilt numpy function.

In [ ]:
import numpy as np
import pandas as pd
np.zeros(10,)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 2) Run the given code and find the dot product of both arrays.

In [ ]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[4 4 9 3]
 [7 6 4 8]
 [8 7 9 9]]
[[2 2 8]
 [2 3 9]
 [7 6 7]
 [3 9 5]]


In [ ]:
#Your code here
np.dot(a,b)

array([[ 88, 101, 146],
       [ 78, 128, 178],
       [120, 172, 235]])

## 3)Read the csv file provided using pandas and display the first 5 entries

In [ ]:
data=pd.read_csv("/content/data.csv")
data.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

## 4)Describe the data with all features.

In [ ]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

## 5)Find the total count of missing values for each feature.

In [ ]:
data.isnull().sum()


OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

There are no null values

## 6)Display all the unique values from the 'DESCRIPTION’ column.

In [ ]:
data['DESCRIPTION'].unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

## 7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

In [ ]:
data.groupby('DESCRIPTION').mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

## 8)Generate a random sample of 10 rows from the data.

In [ ]:
data.sample(10)

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
21        43         Pembina Gorge State Recreation Area  ...   0.000615   0.338800
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487
11        32                      Sully Creek State Park  ...   0.000030   0.024016
18        39             Gunlogson State Nature Preserve  ...   0.000048   0.040465
24        42         Pelican Point State Recreation Area  ...   0.000013   0.026357
0         21                   Fort Stevenson State Park  ...   0.000284   0.135641
17        38         Fahlgren Park State Recreation Area  ...   0.000010   0.013294
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
16        37                  Elkhorn State Natural Area  ...   0.000127   0.067082
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885

[10 rows x 6 columns]

## 9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

In [ ]:
data2=data.assign(New_feature=list(np.random.rand(len(data))))
data2

OBJECTID  ... New_feature
0         21  ...    0.373596
1         22  ...    0.602459
2         23  ...    0.255063
3         24  ...    0.298346
4         25  ...    0.552510
5         26  ...    0.248976
6         27  ...    0.461927
7         28  ...    0.953240
8         29  ...    0.011885
9         30  ...    0.650201
10        31  ...    0.768944
11        32  ...    0.572994
12        35  ...    0.924538
13        36  ...    0.439765
14        33  ...    0.384334
15        34  ...    0.513680
16        37  ...    0.424181
17        38  ...    0.360970
18        39  ...    0.979004
19        40  ...    0.205756
20        41  ...    0.125530
21        43  ...    0.084685
22        44  ...    0.833740
23        45  ...    0.441638
24        42  ...    0.461048

[25 rows x 7 columns]

## 10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [ ]:
data.OBJECTID.mean()

33.0

In [ ]:
data[data.OBJECTID==33]=0

In [ ]:
data

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0         21                   Fort Stevenson State Park  ...   0.000284   0.135641
1         22                      Beaver Lake State Park  ...   0.000129   0.080067
2         23             Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3         24                      Fort Ransom State Park  ...   0.000444   0.128733
4         25                   Grahams Island State Park  ...   0.000469   0.125546
5         26                        Icelandic State Park  ...   0.000461   0.166712
6         27                   Lake Metigoshe State Park  ...   0.000751   0.212196
7         28                  Lewis and Clark State Park  ...   0.000256   0.130420
8         29         Lewis and Clark Interpretive Center  ...   0.000007   0.016774
9         30           Fort Mandan State Recreation Area  ...   0.000005   0.009396
10        31                  Little Missouri State Park  ...   0.003136   0.313756
11        32                      Sully Creek State Park  ...   0.000030   0.024016
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
13        36       Crow Flies High State Recreation Area  ...   0.000120   0.050518
14         0                                           0  ...   0.000000   0.000000
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
16        37                  Elkhorn State Natural Area  ...   0.000127   0.067082
17        38         Fahlgren Park State Recreation Area  ...   0.000010   0.013294
18        39             Gunlogson State Nature Preserve  ...   0.000048   0.040465
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
20        41           Missouri River State Natural Area  ...   0.000083   0.087192
21        43         Pembina Gorge State Recreation Area  ...   0.000615   0.338800
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487
23        45                      Cross Ranch State Park  ...   0.000274   0.180257
24        42         Pelican Point State Recreation Area  ...   0.000013   0.026357

[25 rows x 6 columns]